include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    prefer_const_constructors: true

analyzer:
  errors:
    invalid_annotation_target: ignore